### ISSUE TITLE
Terraform generated sink doesn't seem to work

### ISSUE THREAD

**Issue by pshapiro4broad** [broadinstitute/terraform-cda#7]
To develop the terraform code for the log sink, I first created it directly in the google console and then wrote the TF code for it. When I run the code, it generates a sink that should work the same way the hand generated one does, but it didn't work. I've re-enabled the hand written one so the logs are still being collected, but the TF code needs to be debugged and fixed so the sink doesn't need to be set up manually in all environments.

**Comment by ACharbonneau** [comment]
shifted to broad
